export const DEFAULT_CLUSTER_DISTANCE_MIN = 2;
export const DEFAULT_RECENT_HISTORY_WINDOW = 5;
export const PROMPT_SIMILARITY_HIGH = 0.78;
export const OPTION_SET_SIMILARITY_HIGH = 0.82;
export const MAX_IDENTICAL_MASKTYPE_STREAK = 2;
