export const QA_THRESHOLDS = {
  MIN_SPECIFICITY: 0.6,
  MIN_RECOGNIZABILITY: 0.7,
  MIN_DOMAIN_ANCHORING: 0.75,
  MIN_EVIDENCE_SUPPORT: 0.7,
  MIN_CONCRETENESS: 0.65,
  
  MAX_ABSTRACTION: 0.4,
  MAX_DUPLICATION_RISK: 0.6
};
